swagger: "2.0"
info:
  version: 1.0.0
  title: XMeter
host: localhost
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
security:
 - basicAuth: []
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication.
paths:
  /reliability:
    post:
      summary: High-speed proxy checking
      operationId: checkReliability
      tags:
        - meter
      parameters:
        - in: body
          name: proxy
          schema:
            type: array
            uniqueItems: true
            items:
              type: object
              required:
                - server
                - port
              properties:
                server:
                  type: string
                  x-isnullable: false
                port:
                  type: string
                  x-isnullable: false
      responses:
        "200":
          description: Proxy list
          schema:
            type: array
            items:
              $ref: '#/definitions/ProxyNode'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  ProxyNode:
    properties:
      server:
        type: string
        x-isnullable: false
      port:
        type: string
        x-isnullable: false
      iso_code:
        type: string
        x-isnullable: false
      country:
        type: string
        x-isnullable: false
      ping_time_ms:
        type: integer
        format: int64
        x-isnullable: false
      loss_ratio:
        type: number
        format: double
        x-isnullable: false
      protocol:
        type: string
        x-isnullable: false
  Error:
    required:
      - message
    properties:
      message:
        type: string
        x-isnullable: false
  Principal:
    type: string
